name: volo_test
description: "Test project for Volo"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  auto_route: ^9.2.2
  flutter_bloc: ^9.1.0
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  build_runner: ^2.4.13
  auto_route_generator: ^9.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/fonts/
    - assets/fonts/inter/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter/Inter-VariableFont_slnt,wght.ttf
        - asset: assets/fonts/inter/static/Inter-Black.ttf
        - asset: assets/fonts/inter/static/Inter-Bold.ttf
        - asset: assets/fonts/inter/static/Inter-ExtraBold.ttf
        - asset: assets/fonts/inter/static/Inter-ExtraLight.ttf
        - asset: assets/fonts/inter/static/Inter-Light.ttf
        - asset: assets/fonts/inter/static/Inter-Medium.ttf
        - asset: assets/fonts/inter/static/Inter-Regular.ttf
        - asset: assets/fonts/inter/static/Inter-SemiBold.ttf
        - asset: assets/fonts/inter/static/Inter-Thin.ttf
